POST http://localhost:8081/category/create
Content-Type: application/json

{
    "Description":"pen"
}
###
POST http://localhost:3000/users/create
Content-Type: application/json

{
    "username":"hello",
    "age":"22",
    "password":"qweqw"
}

GET http://localhost:8081/category/show
Content-Type: application/json
{
    
}